WebApplication2/Models/AlunoModel2.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models
{
    public class AlunoModel2
    {
        public string Nome { get; set; }
        public string Curso { get; set; }
        public DateTime Matricula { get; set; }
        public int Faltas { get; set; }

        public AlunoModel2()
        {
            Nome = "Michael";
            Curso = "Desenvolvimento de Sistemas";
            Faltas = 1;
            Matricula = new DateTime(2023,1,27);
        }

        public static AlunoModel2 CriarAluno()
        {
            var aluno = new AlunoModel2();
            aluno.Nome = "Emerson";
            return aluno;
        }
        public static List<AlunoModel2> CriarLista()
        {
            var lista = new List<AlunoModel2>();
           // lista.Add(new AlunoModel2());
           // lista.Add(AlunoModel2.CriarAluno());
           lista.Add(new AlunoModel2() { Nome= "Gabriel Gassner", Curso = "DS", Faltas = 5, Matricula = DateTime.Now});
           lista.Add(new AlunoModel2() { Nome= "Daniel Souza", Curso = "DS", Faltas = 5, Matricula = DateTime.Now});
           lista.Add(new AlunoModel2() { Nome= "Rhuan", Curso = "DS", Faltas = 5, Matricula = DateTime.Now});
           lista.Add(new AlunoModel2() { Nome= "Rodrigo", Curso = "DS", Faltas = 5, Matricula = DateTime.Now});

            return lista;
        }
    }
}

WebApplication2/Models/CursoModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models
{
    public class CursoModel
    {
        public string Nome { get; set; }
        public string Modalidade { get; set; }
        public int Vagas { get; set; }

        public static List<CursoModel> CriarLista()
        {
            var lista = new List<CursoModel>();

            lista.Add(new CursoModel() { Nome = "Desenvolvimento de Sistemas", Modalidade = "Presencial", Vagas = 40});
            lista.Add(new CursoModel() { Nome = "Contabilidade", Modalidade = "Semi-Presencial", Vagas = 40});
            lista.Add(new CursoModel() { Nome = "Administração", Modalidade = "EAD", Vagas = 40});
            lista.Add(new CursoModel() { Nome = "Edificações", Modalidade = "Presencial (20% EAD)", Vagas = 80});
            lista.Add(new CursoModel() { Nome = "Recursos Humanos", Modalidade = "EAD", Vagas = 40});

            return lista;
        }
    }
}

WebApplication2/Models/ErrorViewModel.cs
using System;

namespace WebApplication1.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplication2/Controllers/Aluno2Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class Aluno2Controller : Controller
    {
        // GET: Aluno2
        public ActionResult Index()
        {
            return View(AlunoModel2.CriarLista());
        }

        // GET: Aluno2/Details/5
        public ActionResult Details(int id)
        {
            var aluno = AlunoModel2.CriarLista()[id];
            return View(aluno);


        }

        // GET: Aluno2/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Aluno2/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AlunoModel2 collection)
        {
            try
            {
                // TODO: Add insert logic here


                return RedirectToAction(nameof(Index));
                //return RedirectToAction(nameof(Details)); ***caso queira mandar o formulario pra pagina details depois***
            }
            catch
            {
                return View();
            }
        }

        // GET: Aluno2/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Aluno2/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Aluno2/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Aluno2/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

WebApplication2/Controllers/CursoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    

    public class CursoController : Controller
    {
        // GET: Curso
        public ActionResult Index()
        {
            return View(CursoModel.CriarLista());
        }

        // GET: Curso/Details/5
        public ActionResult Details(int id)
        {
            var curso = CursoModel.CriarLista()[id];
            return View(curso);
        }

        // GET: Curso/Create
        public ActionResult Create()
        {
            var curso = CursoModel.CriarLista();

            return View();
        }

        // POST: Curso/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CursoModel collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Curso/Edit/5
        public ActionResult Edit(int id)
        {
            var curso = CursoModel.CriarLista()[id];

            return View(curso);

        }

        // POST: Curso/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit()
        {

            return View();
        }

        // GET: Curso/Delete/5
        public ActionResult Delete(int id)
        {
            var curso = CursoModel.CriarLista()[id];

            //  var curso = CursoModel.CriarLista().Where(o => o.Id == Id).FirstOrDefault();
            return View(curso);
        }

        // POST: Curso/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(CursoModel Curso, IFormCollection collection)
        {


            return RedirectToAction("Index");
        }
    }
}
  

WebApplication2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult ExibirAluno()
        {
            var aluno = new AlunoModel2()
            {
                Nome = "Michael Douglas",
                Curso = "Desenvolvimento de Sistemas"
            };
            return View(aluno);
        }

        public IActionResult Pratica()
        {
            return View();
        }
        
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplication2/Views/Aluno2/Create.cshtml
@model WebApplication1.Models.AlunoModel2

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>AlunoModel2</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Curso" class="control-label"></label>
                <input asp-for="Curso" class="form-control" />
                <span asp-validation-for="Curso" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Matricula" class="control-label"></label>
                <input asp-for="Matricula" class="form-control" />
                <span asp-validation-for="Matricula" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Faltas" class="control-label"></label>
                <input asp-for="Faltas" class="form-control" />
                <span asp-validation-for="Faltas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication2/Views/Aluno2/Details.cshtml
@model WebApplication1.Models.AlunoModel2

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>AlunoModel2</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Curso)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Curso)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Matricula)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Matricula)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Faltas)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Faltas)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

WebApplication2/Views/Aluno2/Edit.cshtml
@model WebApplication1.Models.AlunoModel2

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>AlunoModel2</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Curso" class="control-label"></label>
                <input asp-for="Curso" class="form-control" />
                <span asp-validation-for="Curso" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Matricula" class="control-label"></label>
                <input asp-for="Matricula" class="form-control" />
                <span asp-validation-for="Matricula" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Faltas" class="control-label"></label>
                <input asp-for="Faltas" class="form-control" />
                <span asp-validation-for="Faltas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication2/Views/Aluno2/Index.cshtml
@model IEnumerable<WebApplication1.Models.AlunoModel2>

@{
    ViewData["Title"] = "Index";
}

<h2>Aluno</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Curso)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Matricula)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Faltas)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Curso)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Matricula)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Faltas)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { id = ((List<AlunoModel2>)Model).IndexOf(item)}) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

WebApplication2/Views/Curso/Create.cshtml
@model WebApplication1.Models.CursoModel

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>CursoModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Modalidade" class="control-label"></label>
                <input asp-for="Modalidade" class="form-control" />
                <span asp-validation-for="Modalidade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Vagas" class="control-label"></label>
                <input asp-for="Vagas" class="form-control" />
                <span asp-validation-for="Vagas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication2/Views/Curso/Delete.cshtml
@model WebApplication1.Models.CursoModel

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CursoModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Modalidade)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Modalidade)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Vagas)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Vagas)
        </dd>
        <dt>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebApplication2/Views/Curso/Details.cshtml
@model WebApplication1.Models.CursoModel

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>CursoModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Modalidade)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Modalidade)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Vagas)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Vagas)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

WebApplication2/Views/Curso/Edit.cshtml
@model WebApplication1.Models.CursoModel

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>CursoModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Modalidade" class="control-label"></label>
                <input asp-for="Modalidade" class="form-control" />
                <span asp-validation-for="Modalidade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Vagas" class="control-label"></label>
                <input asp-for="Vagas" class="form-control" />
                <span asp-validation-for="Vagas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication2/Views/Curso/Index.cshtml
@model IEnumerable<WebApplication1.Models.CursoModel>

@{
    ViewData["Title"] = "Curso";
}

<h2>Curso</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Modalidade)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Vagas)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Modalidade)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Vagas)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { id = ((List<CursoModel>)Model).IndexOf(item) }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

WebApplication2/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

WebApplication2/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebApplication2/Views/Home/ExibirAluno.cshtml
@model WebApplication1.Models.AlunoModel2

@{
    ViewData["Title"] = "ExibirAluno";
}

<h2>Exibir</h2>

<div>
    <h4>Aluno</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Curso)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Curso)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

WebApplication2/Views/Home/Pratica.cshtml
<h2>Pratica</h2>

WebApplication2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">WebApplication1</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Pratica">Pratica</a></li>
                    <li><a asp-area="" asp-controller="Aluno2" asp-action="Index">Aluno</a></li>
                    <li><a asp-area="" asp-controller="Curso" asp-action="Index">Curso</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2023 - WebApplication1</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>